# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
name: David Craig Penner
email: davidcraigpenner@gmail.com
description: > # this means to ignore newlines until "url:"
  David Craig Penner's personal website.
footer_text: >
#Powered by <a href="http://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
#Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.
#Photos from <a href="https://unsplash.com" target="_blank">Unsplash</a>.

url: https://www.davidcraigpenner.com # the base hostname & protocol for your site
baseurl: # the subpath of your site, e.g. /blog/
last_updated: 2019-10-31 # leave blank if you don't want to display last updated

encoding: utf-8

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------
github_username: davidcraigpenner # your GitHub username
linkedin_username: davidcraigpenner # your LinkedIn username
twitter_username: # your Twitter handle
scholar_userid: Ix_acVAAAAAJ # your Google Scholar ID
orcid_id: 0000-0001-9234-9768 # your ORCID ID
medium_username: # your Medium username
quora_username: # your Quora username
researchgate_username: David_Craig_Penner # your ResearchGate username

#contact_note: >
#  You can even add a little note about which of these is the best way to reach you.

google_analytics: UA-143601888-1 # your google-analytics code

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------
#blog_name: al-folio
#blog_description: a simple whitespace theme for academics

# Pagination
#paginate: 4
#permalink: /blog/:year/:title/
#paginate_path: /blog/page:num/

#text:
#  pagination:
#    newer: 'Newer'
#    older: 'Older'

# Comments
#disqus_shortname: al-folio # put your disqus shortname

# Optional features
show_social_icons:  true
enable_anchorjs:    true
enable_katex:       true

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
#collections:
#  news:
#    defaults:
#      layout: post
#    output: true
#    permalink: /news/:path/
#  projects:
#    output: true
#    permalink: /projects/:path/

#news_limit: 5

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown
highlighter: pygments

# Includes & excludes
include: ['_pages']
exclude: [vendor]
exclude: ['_posts']

# Plug-ins
plugins:
    - jekyll-email-protect
    - jekyll-paginate
    - jekyll/scholar
    - jemoji

# Jekyll-Scholar
scholar:

  last_name: Craig Penner

  style: /_bibliography/APS_Qi.csl # ieee.csl
  locale: en

  sort_by: year, month
  order: descending
  bibliography_list_attributes:
    reversed: "reversed" # This reverses the numbering of publications in the sorted group.    
  
  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib

  replace_strings: true
  join_strings: true
  
  use_raw_bibtex_entry: false
  bibtex_filters:
    #- superscript
    - latex
    #- markdown
  
  bibtex_skip_fields:
    - abstract
    - month_numeric
    - pdf
    
  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
jquery_version: "1.12.4"
katex_version: "0.9.0"
anchorjs_version: "3.2.2"
